### ISSUE TITLE
Consider 3-D printing the case(s)

### ISSUE THREAD

**Issue by jberkus** [rgardler/BigLittleChallenge#1]
Instead of legos, you can 3-D print a simple box out of translucent plastic, and then use brass standoffs to hold the boards.  Example:

https://fuzzychef.smugmug.com/Computers/ContanersContainersContainers/i-p4c7Gjk/A

Lemme know what other info you need.

**Comment by SorraTheOrc** [comment]
This is a really good idea, and it gives me a really good reason to buy a 3D printer!

**Comment by SorraTheOrc** [comment]
Thank @jberkus I added you link to https://github.com/rgardler/BigLittleChallenge/blob/master/docs/pikube/index.md
